---
abstract: 'Moose type constraints for strings or string-like objects'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Stringlike
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  MooseX::Types::Stringlike:
    file: lib/MooseX/Types/Stringlike.pm
    version: 0.001
requires:
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  overload: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Types-Stringlike
  homepage: https://github.com/dagolden/moosex-types-stringlike
  repository: https://github.com/dagolden/moosex-types-stringlike.git
version: 0.001
